# Use the README file as a reference to customize settings.

Advertisement:
  fields:
    default: user_id, content, role
    form: user_id, content, role
  relationships: 
  application: Application
