# Use the README file as a reference to customize settings.

BlockedRelationship:
  fields:
    default: user_id, blocked_user_id
    form: user_id, blocked_user_id
  relationships: 
  application: Application
