# Use the README file as a reference to customize settings.

TeacherRelationship:
  fields:
    default: user_id, subject_id
    form: user_id, subject_id
  relationships: 
  application: Application
